Repository pykeen/pykeen, pull requests merged in 2020-08, with the labels that each got.

#69 Generalize specification of tracker
  README.md
  docs/source/tutorial/using_mlflow.rst
  src/pykeen/cli.py
  src/pykeen/hpo/hpo.py
  src/pykeen/models/cli/builders.py
  src/pykeen/pipeline.py
  src/pykeen/templates/README.md
  src/pykeen/trackers.py
Labels: enhancement

#56 Document PyKEEN's performance tweaks
  docs/source/index.rst
  docs/source/tutorial/performance.rst
Labels: documentation

#68 A new tracker for Weights & Biases
  .gitignore
  README.md
  docs/source/index.rst
  docs/source/tutorial/using_mlflow.rst
  docs/source/tutorial/using_wandb.rst
  setup.cfg
  src/pykeen/pipeline.py
  src/pykeen/templates/README.md
  src/pykeen/trackers.py
Labels: New Tracker

#83 Add HPO documentation for constrained evaluation
  docs/source/tutorial/understanding_evaluation.rst
  src/pykeen/hpo/hpo.py
Labels: documentation, enhancement
