Repository pykeen/pykeen, pull requests merged in 2020-11, with the labels that each got.

#136 Make get_embedding_in_canonical_shape part of Embedding class
  src/pykeen/datasets/base.py
  src/pykeen/models/base.py
  src/pykeen/models/unimodal/kg2e.py
  src/pykeen/models/unimodal/ntn.py
  src/pykeen/models/unimodal/rgcn.py
  src/pykeen/models/unimodal/simple.py
  src/pykeen/models/unimodal/trans_d.py
  src/pykeen/nn/emb.py
  src/pykeen/triples/triples_factory.py
  src/pykeen/utils.py
  tests/test_models.py
  tests/test_utils.py
Labels: enhancement

#137 Improve checking for abstract classes and applying post init hooks
  src/pykeen/models/base.py
  src/pykeen/models/cli/builders.py
  src/pykeen/models/unimodal/rgcn.py
  tests/test_models.py
Labels: enhancement

#139 Add MLflow set tags function
  AUTHORS.md
  docs/source/tutorial/trackers/using_mlflow.rst
  src/pykeen/trackers.py
Labels: enhancement

#156 Add DRKG and better dataset testing
  README.md
  setup.cfg
  src/pykeen/datasets/base.py
  src/pykeen/datasets/drkg.py
  src/pykeen/triples/triples_factory.py
  tests/cases.py
  tests/constants.py
  tests/resources/hpo_complex_nations.json
  tests/resources/nations.tar.gz
  tests/test_datasets.py
Labels: New Dataset

#159 Add OGB KG completion datasets
  README.md
  setup.cfg
  src/pykeen/datasets/__init__.py
  src/pykeen/datasets/base.py
  src/pykeen/datasets/ogb.py
Labels: New Dataset

#170 Fix compose
  src/pykeen/utils.py
  tests/test_models.py
  tests/test_utils.py
Labels: bug
