Repository pykeen/pykeen, pull requests merged in 2020-12, with the labels that each got.

#185 Automatically add links to docs in README
  README.md
  src/pykeen/cli.py
Labels: documentation

#188 Add better type hints for random state and helper function
  src/pykeen/datasets/base.py
  src/pykeen/datasets/drkg.py
  src/pykeen/datasets/hetionet.py
  src/pykeen/triples/triples_factory.py
  src/pykeen/typing.py
  src/pykeen/utils.py
Labels: documentation, enhancement

#183 Add neptune.ai tracker
  .appveyor.yml
  .appveyor_on_request.yml
  .github/workflows/tests.yml
  .github/workflows/tests_master.yml
  README.md
  docs/source/tutorial/trackers/index.rst
  docs/source/tutorial/trackers/using_mlflow.rst
  docs/source/tutorial/trackers/using_neptune.rst
  setup.cfg
  src/pykeen/trackers.py
  src/pykeen/trackers/__init__.py
  src/pykeen/trackers/base.py
  src/pykeen/trackers/mlflow.py
  src/pykeen/trackers/neptune.py
  src/pykeen/trackers/wandb.py
  src/pykeen/utils.py
  tox.ini
Labels: New Tracker

#181 Better explain where models' defaults come from
  README.md
  docs/source/references.rst
  src/pykeen/hpo/__init__.py
  src/pykeen/pipeline.py
  src/pykeen/templates/README.md
Labels: documentation

#189 Reorganize Loss class hierarchy
  src/pykeen/losses.py
  tests/test_losses.py
Labels: enhancement

#127 Add tutorial for custom models
  docs/source/conf.py
  docs/source/extending/extending_models.rst
  docs/source/extending/index.rst
  docs/source/index.rst
Labels: documentation

#194 Add windows testing to GitHub Actions
  .github/workflows/tests.yml
  .github/workflows/tests_master.yml
  MANIFEST.in
  README.md
  src/pykeen/templates/README.md
Labels: meta

#192 Switch config lookup to PyStow
  docs/source/index.rst
  docs/source/reference/constants.rst
  setup.cfg
  src/pykeen/constants.py
  src/pykeen/datasets/base.py
Labels: meta

#199 Add nations literal dataset and add tests for LiteralE models
  src/pykeen/datasets/base.py
  src/pykeen/datasets/literal_base.py
  src/pykeen/datasets/nations/__init__.py
  src/pykeen/datasets/nations/literals.txt
  src/pykeen/experiments/validate.py
  src/pykeen/models/base.py
  src/pykeen/models/multimodal/complex_literal.py
  src/pykeen/models/multimodal/distmult_literal.py
  src/pykeen/models/unimodal/complex.py
  src/pykeen/nn/emb.py
  tests/test_models.py
  tests/test_multimodal.py
Labels: New Dataset

#123 Add checkpoint saving and loading functionality to training loop
  docs/source/index.rst
  docs/source/tutorial/checkpoints.rst
  docs/source/tutorial/first_steps.rst
  src/pykeen/constants.py
  src/pykeen/models/base.py
  src/pykeen/pipeline.py
  src/pykeen/stoppers/early_stopping.py
  src/pykeen/stoppers/stopper.py
  src/pykeen/training/training_loop.py
  tests/test_pipeline.py
  tests/test_training.py
Labels: enhancement

#201 Add triple generation utilities
  src/pykeen/triples/generation.py
  src/pykeen/triples/utils.py
  tests/test_generation.py
Labels: enhancement

#203 Extend documentation for negative sampling
  README.md
  src/pykeen/sampling/__init__.py
  src/pykeen/sampling/basic_negative_sampler.py
  src/pykeen/sampling/bernoulli_negative_sampler.py
Labels: documentation

#193 Switch internal usage to ID-based triples
  src/pykeen/datasets/base.py
  src/pykeen/triples/generation.py
  src/pykeen/triples/leakage.py
  src/pykeen/triples/triples_factory.py
  src/pykeen/triples/triples_numeric_literals_factory.py
  src/pykeen/triples/utils.py
  src/pykeen/typing.py
  src/pykeen/utils.py
  tests/test_generation.py
  tests/test_leakage.py
  tests/test_triples_factory.py
  tests/test_utils.py
Labels: enhancement

#187 Optimize triples splitting and cleanup algorithms
  MANIFEST.in
  benchmarking/benchmark_splitting.py
  src/pykeen/datasets/__init__.py
  src/pykeen/evaluation/evaluator.py
  src/pykeen/triples/splitting.py
  src/pykeen/triples/triples_factory.py
  src/pykeen/utils.py
  tests/test_triples_factory.py
Labels: enhancement

#160 Add ConceptNet
  README.md
  setup.cfg
  src/pykeen/datasets/__init__.py
  src/pykeen/datasets/base.py
  src/pykeen/datasets/conceptnet.py
Labels: New Dataset

#211 Add generalized metadata storage to TriplesFactory and improve repr
  src/pykeen/triples/triples_factory.py
  tests/test_triples_factory.py
Labels: enhancement

#213 Add Clinical Knowledge Graph (CKG) dataset
  README.md
  setup.cfg
  src/pykeen/datasets/__init__.py
  src/pykeen/datasets/base.py
  src/pykeen/datasets/ckg.py
Labels: New Dataset

#208 Predict with Inverse Triples
  src/pykeen/experiments/inverse_stability.py
  src/pykeen/models/base.py
  src/pykeen/models/multimodal/complex_literal.py
Labels: documentation, enhancement

#215 Update documentation, typing, and utils
  MANIFEST.in
  src/pykeen/experiments/transh/wang2014_transh_fb15k.json
  src/pykeen/experiments/transh/wang2014_transh_wn18.json
  src/pykeen/losses.py
  src/pykeen/models/__init__.py
  src/pykeen/models/base.py
  src/pykeen/models/cli/builders.py
  src/pykeen/models/cli/options.py
  src/pykeen/models/multimodal/complex_literal.py
  src/pykeen/models/multimodal/distmult_literal.py
  src/pykeen/models/unimodal/complex.py
  src/pykeen/models/unimodal/conv_e.py
  src/pykeen/models/unimodal/conv_kb.py
  src/pykeen/models/unimodal/distmult.py
  src/pykeen/models/unimodal/ermlp.py
  src/pykeen/models/unimodal/ermlpe.py
  src/pykeen/models/unimodal/hole.py
  src/pykeen/models/unimodal/kg2e.py
  src/pykeen/models/unimodal/ntn.py
  src/pykeen/models/unimodal/proj_e.py
  src/pykeen/models/unimodal/rescal.py
  src/pykeen/models/unimodal/rgcn.py
  src/pykeen/models/unimodal/rotate.py
  src/pykeen/models/unimodal/simple.py
  src/pykeen/models/unimodal/structured_embedding.py
  src/pykeen/models/unimodal/trans_d.py
  src/pykeen/models/unimodal/trans_e.py
  src/pykeen/models/unimodal/trans_h.py
  src/pykeen/models/unimodal/trans_r.py
  src/pykeen/models/unimodal/tucker.py
  src/pykeen/models/unimodal/unstructured_model.py
  src/pykeen/nn/emb.py
  src/pykeen/nn/init.py
  src/pykeen/regularizers.py
  src/pykeen/sampling/__init__.py
  src/pykeen/sampling/negative_sampler.py
  src/pykeen/triples/splitting.py
  src/pykeen/triples/triples_factory.py
  src/pykeen/typing.py
  src/pykeen/utils.py
  tests/test_early_stopping.py
  tests/test_evaluators.py
  tests/test_hpo.py
  tests/test_model_mode.py
  tests/test_models.py
  tests/test_utils.py
  tox.ini
Labels: documentation, enhancement

#225 Extend normalization to other p norms
  src/pykeen/regularizers.py
  tests/test_regularizers.py
Labels: enhancement
