Repository pykeen/pykeen, pull requests merged in 2021-06, with the labels that each got.

#473 💾 🔍 Use class resolver for datasets
  benchmarking/benchmark_splitting.py
  docs/Makefile
  docs/source/reference/lookup.rst
  setup.cfg
  src/pykeen/cli.py
  src/pykeen/datasets/__init__.py
  src/pykeen/datasets/cli.py
  src/pykeen/experiments/validate.py
  src/pykeen/hpo/hpo.py
  src/pykeen/nn/emb.py
  src/pykeen/pipeline/api.py
  tests/test_datasets/test_loading.py
  tox.ini
Labels: enhancement, 💾 Dataset

#474 ⛏️ 🦔 Update docs for using learned embeddings
  docs/source/extending/models.rst
  docs/source/tutorial/first_steps.rst
  src/pykeen/models/base.py
Labels: documentation

#416 📡 📉 Adding Tensorboard Tracker
  CHANGELOG.rst
  README.md
  docs/source/installation.rst
  docs/source/tutorial/trackers/index.rst
  docs/source/tutorial/trackers/using_tensorboard.rst
  setup.cfg
  src/pykeen/trackers/__init__.py
  src/pykeen/trackers/tensorboard.py
  tests/test_trackers.py
Labels: 🐺 Tracker, 💎 New Component

#444 🩹 👾 Fix ERMLP functional form
  src/pykeen/models/resolve.py
  src/pykeen/nn/functional.py
  src/pykeen/pipeline/api.py
  tests/cases.py
  tox.ini
Labels: bug

#497 📖 ♻️ Update example code in "first steps" tutorial
  docs/source/tutorial/first_steps.rst
  src/pykeen/evaluation/evaluator.py
Labels: documentation

#502 🍺 📖 Add link to BYOD to readme
  README.md
  src/pykeen/templates/README.md
Labels: documentation

#503 🪟 🪲 Catch FileNotFoundError thrown on Windows/Anaconda
  src/pykeen/version.py
Labels: bug

#504 📜 🔧 Fixed docstring for ComplEx interaction: conjugate for Eq1 and fixed Eq2
  src/pykeen/models/unimodal/complex.py
Labels: documentation

#507 🥰 🌫️ Add DistMA interaction
  README.md
  src/pykeen/models/__init__.py
  src/pykeen/models/unimodal/__init__.py
  src/pykeen/models/unimodal/distma.py
  src/pykeen/nn/functional.py
  src/pykeen/nn/modules.py
  tests/test_models.py
  tests/test_nn/test_modules.py
Labels: 💃 Model, 💎 New Component

#511 💾 🧪 WD50K (triples) dataset
  README.md
  docs/source/references.rst
  setup.cfg
  src/pykeen/datasets/__init__.py
  src/pykeen/datasets/wd50k.py
Labels: 💾 Dataset
