Repository pykeen/pykeen, pull requests merged in 2021-04, with the labels that each got.

#379 ♻️ 📚 Update Colab and Kaggle installation docs
  docs/source/installation.rst
Labels: documentation

#378 🎁 📐 Add AMRI and update docs
  README.md
  docs/source/index.rst
  docs/source/reference/evaluation.rst
  docs/source/reference/evaluation/index.rst
  docs/source/reference/evaluation/rank_based.rst
  docs/source/reference/evaluation/threshold_based.rst
  docs/source/references.rst
  docs/source/tutorial/understanding_evaluation.rst
  setup.cfg
  src/pykeen/cli.py
  src/pykeen/evaluation/__init__.py
  src/pykeen/evaluation/evaluator.py
  src/pykeen/evaluation/rank_based_evaluator.py
  src/pykeen/evaluation/sklearn.py
  src/pykeen/templates/README.md
  tests/test_early_stopping.py
  tests/test_evaluators.py
Labels: 📐 New Metric

#367 🥥 💃 Add QuatE
  README.md
  src/pykeen/models/__init__.py
  src/pykeen/models/unimodal/__init__.py
  src/pykeen/models/unimodal/quate.py
  src/pykeen/nn/functional.py
  src/pykeen/nn/init.py
  src/pykeen/nn/modules.py
  tests/cases.py
  tests/test_models.py
  tests/test_nn/test_modules.py
Labels: 💃 New Model

#16 🧰 💾 Add utilities to analyse datasets
  docs/source/reference/datasets.rst
  src/pykeen/datasets/analysis.py
  src/pykeen/datasets/base.py
  tests/test_datasets/test_analysis.py
Labels: 🎶 discussion

#382 💃🕷️ Implement CompGCN
  README.md
  src/pykeen/models/__init__.py
  src/pykeen/models/unimodal/__init__.py
  src/pykeen/models/unimodal/compgcn.py
  src/pykeen/nn/compositions.py
  src/pykeen/nn/emb.py
  src/pykeen/nn/functional.py
  tests/cases.py
  tests/test_models.py
  tests/test_nn/test_emb.py
Labels: 💃 New Model

#301 ♻️ ❤️ Refactor Ablation Pipeline
  docs/source/tutorial/running_ablation.rst
  src/pykeen/ablation/__init__.py
  src/pykeen/ablation/ablation.py
  src/pykeen/experiments/cli.py
  src/pykeen/hpo/hpo.py
  src/pykeen/models/cli/builders.py
  src/pykeen/pipeline/api.py
  tests/test_hpo.py
  tox.ini
Labels: documentation, enhancement

#245 🧨 💎 Add literal interaction and outline for tests
  docs/source/reference/nn/combinations.rst
  docs/source/reference/nn/index.rst
  docs/source/reference/nn/message_passing.rst
  docs/source/reference/nn/weighting.rst
  setup.cfg
  src/pykeen/datasets/nations/__init__.py
  src/pykeen/models/__init__.py
  src/pykeen/models/base.py
  src/pykeen/models/multimodal/__init__.py
  src/pykeen/models/multimodal/base.py
  src/pykeen/models/multimodal/complex_literal.py
  src/pykeen/models/multimodal/distmult_literal.py
  src/pykeen/nn/combinations.py
  src/pykeen/nn/emb.py
  src/pykeen/nn/modules.py
  src/pykeen/triples/triples_numeric_literals_factory.py
  src/pykeen/typing.py
  tests/cases.py
  tests/test_models.py
  tests/test_multimodal.py
  tests/test_nn/test_emb.py
  tests/test_nn/test_modules.py
  tests/test_nn/test_modules_literal.py
Labels: enhancement

#122 🪢 🦍 Make pipeline more robust
  docs/source/tutorial/performance.rst
  src/pykeen/pipeline/api.py
Labels: enhancement

#398 🎚️🎛️ Flexibly Define Positive Triples for Filtering
  docs/source/index.rst
  docs/source/tutorial/understanding_evaluation.rst
  src/pykeen/evaluation/evaluator.py
  src/pykeen/evaluation/rank_based_evaluator.py
  src/pykeen/evaluation/sklearn.py
  src/pykeen/hpo/hpo.py
  src/pykeen/models/unimodal/conv_e.py
  src/pykeen/pipeline/api.py
  src/pykeen/sampling/filtering.py
  tests/test_evaluators.py
  tests/test_pipeline.py
Labels: enhancement
