Repository pykeen/pykeen, pull requests merged in 2022-03, with the labels that each got.

#417 🦞 💿 Negative sampling in data loader
  src/pykeen/models/predict.py
  src/pykeen/sampling/basic_negative_sampler.py
  src/pykeen/sampling/bernoulli_negative_sampler.py
  src/pykeen/sampling/filtering.py
  src/pykeen/sampling/negative_sampler.py
  src/pykeen/sampling/pseudo_type.py
  src/pykeen/training/schlichtkrull_sampler.py
  src/pykeen/training/slcwa.py
  src/pykeen/training/training_loop.py
  src/pykeen/triples/analysis.py
  src/pykeen/triples/instances.py
  src/pykeen/triples/triples_factory.py
  src/pykeen/triples/triples_numeric_literals_factory.py
  src/pykeen/triples/utils.py
  src/pykeen/utils.py
  tests/cases.py
  tests/test_sampling/cases.py
  tests/test_sampling/test_negative_samplers.py
  tests/test_splitting.py
Labels: enhancement, 🦞 Negative Sampler

#821 🍌🍍 Fix ValueError during size probing on GPU machines
  src/pykeen/evaluation/rank_based_evaluator.py
Labels: bug

#830 💾 ♻️ Refactor dataset utility code
  src/pykeen/datasets/__init__.py
  src/pykeen/datasets/base.py
  src/pykeen/datasets/cli.py
  src/pykeen/datasets/utils.py
  src/pykeen/pipeline/api.py
  tests/test_datasets/test_cache.py
Labels: 💾 Dataset

#832 💾 🐕 Update dataset registration
  README.md
  docs/source/installation.rst
  setup.cfg
  src/pykeen/datasets/__init__.py
  src/pykeen/datasets/nations/__init__.py
Labels: bug

#833 🦜 📖 Refactor NodePiece and improve documentation
  docs/source/index.rst
  docs/source/reference/nn/index.rst
  docs/source/reference/nn/node_piece.rst
  docs/source/reference/nn/perceptron.rst
  docs/source/tutorial/node_piece.rst
  setup.cfg
  src/pykeen/models/unimodal/node_piece.py
  src/pykeen/nn/node_piece.py
  src/pykeen/nn/node_piece/__init__.py
  src/pykeen/nn/node_piece/anchor_search.py
  src/pykeen/nn/node_piece/anchor_selection.py
  src/pykeen/nn/node_piece/loader.py
  src/pykeen/nn/node_piece/representations.py
  src/pykeen/nn/node_piece/tokenization.py
  src/pykeen/nn/node_piece/utils.py
  tests/test_nn/test_node_piece.py
  tests/test_nn/test_representation.py
  tox.ini
Labels: documentation
